<?php
$unidad = [ '1' => 'UNIDAD DE SEGUROS', '2' => 'UNIDAD DE APOYO A LA DOCENCIA E INVESTIGACIÓN', '3' => 'UNIDAD DE GESTIÓN A LA CALIDAD',
'4' => 'UNIDAD DE ADMINISTRACIÓN', '5' => 'UNIDAD DE PLANEAMIENTO ESTRATÉGICO', '6' => 'UNIDAD DE ESTADÍSTICA E INFORMÁTICA',
'7' => 'UNIDAD DE ASESORÍA LEGAL', '8' => 'UNIDAD DE EPIDEMIOLOGÍA Y SALUD AMBIENTAL', '9' => 'ORGANO DE CONTROL INTERNO',
'10' => 'DIRECCIÓN EJECUTIVA', '11' => 'SERVICIO DE APOYO AL DIAGNOSTICO', '12' => 'SERVICIO DE APOYO AL TRATAMIENTO',
'13' => 'SERVICIO DE EMERGENCIA', '14' => 'SERVICIO DE ENFERMERÍA', '15' => 'SERVICIO DE CONSULTORIO EXTERNO Y HOSPITALIZACIÓN',
'16' => 'SERVICIO DE ODONTO ESTOMATOLOGÍA', '17' => 'SERVICIO DE GINECO OBSTETRICIA', '18' => 'SERVICIO DE PEDIATRÍA',
'19' => 'SERVICIO DE CIRUGÍA Y ANESTESIOLOGÍA', '20' => 'SERVICIO DE MEDICINA'];
$area = ['1' => 'ÁREA DE PERSONAL' , '2' => 'ÁREA DE LOGÍSTICA','3' => 'ÁREA DE ECONOMÍA', '4' => 'ÁREA DE SERVICIOS GENERALES Y MANTENIMIENTO',
'5' => 'ÁREA DE DIAGNÓSTICO POR IMÁGENES', '6' => 'ÁREA DE LABORATORIO', '7' => 'ÁREA DE NUTRICIÓN Y DIETA', '8' => 'ÁREA DE SERVICIO SOCIAL',
'9' => 'ÁREA DE PSICOLOGÍA', '10' => 'ÁREA DE FARMACIA' , '11' => 'CONSULTA EXTERNA', '12' => 'HOSPITALIZACIÓN', '13' => 'ÁREA DE MEDICINA INTERNA',
'14' => 'ÁREA DE MEDICINA ESPECIALIZADA', '15' => 'ÁREA DE CIRUGÍA GENERAL', '16' => 'ÁREA DE ANESTESIOLOGÍA', '17' => 'ÁREA DE PEDIATRÍA MEDICO',
'18' => 'ÁREA DE NEONATOLOGÍA MEDICO', '19' => 'ÁREA DE GINECOLOGIA MEDICO', '20' => 'ÁREA DE OBSTETRICIA OBSTETRA', '21' => 'ÁREA DE ODONTOESTOMATOLOGIA',
'22' => 'ODONTOLOGO', '23' => 'PP ENFERMEDADES METAXENICAS Y ZOONOSIS', '24' => 'PP ENFERMEDADES NO TRANSMISIBLES', '25' => 'PP ARTICULADO NUTRICIONAL',
'26' => 'PP PREVENCIÓN Y CONTROL DE CÁNCER', '27' => 'PP SALUD MATERNO NEONATAL', '28' => 'PP TBC VIH SIDA', '29' => 'PP REDUCCIÓN DE VULNERABILIDAD Y ATENCIÓN DE EMERGENCIAS POR DESASTRES',
'30' => 'SUB DIRECCIÓN', '31' => 'ÁREA DE SECRETARIA', '32' => 'ÁREA DE PRESUPUESTO', '33' => 'ÁREA DE ORGANIZACIÓN', '34' => 'ÁREA DE PLANEAMIENTO', '35' => 'ÁREA DE PROYECTOS DE INVERSIÓN',
'36' => 'ÁREA  DE SALUD AMBIENTAL', '37' => 'ÁREA DE EPIDEMIOLOGÍA', '38' => 'ÁREA DE MUESTRA I', '39' => 'ÁREA DE ESTUDIOS E INVESTIGACIÓN', '40' => 'ÁREA DE ESTADÍSTICA', '41' => 'ÁREA DE INFORMÁTICA',
'42' => 'ÁREA DE DOCENCIA', '43' => 'ÁREA DE INVESTIGACIÓN'];